### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by tiagofrepereira2012** [meta00/vital_sqi#98]
It is not possible to pip install this package using python 3.10 (Ubuntu 22.04 with conda).

There is an issue with numba, as you can see on the log below

```sh
     error: Command "gcc -pthread -B /home/miniconda3/envs/vital_exploratory/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/miniconda3/envs/vital_exploratory/include -fPIC -O2 -isystem /home/miniconda3/envs/vital_exploratory/include -fPIC -I/home/miniconda3/envs/vital_exploratory/lib/python3.10/site-packages/numpy/core/include -I/home/miniconda3/envs/vital_exploratory/include/python3.10 -c numba/_dispatcher.c -o build/temp.linux-x86_64-cpython-310/numba/_dispatcher.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      /home/miniconda3/envs/vital_exploratory/bin/python /tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py
      LLVM version... 14.0.0
      
      Traceback (most recent call last):
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 191, in <module>
          main()
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 181, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 143, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '14.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
      
      error: command '/home/miniconda3/envs/vital_exploratory/bin/python' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
Installing collected packages: llvmlite, lazy-loader, joblib, future, et-xmlfile, Cython, chardet, audioread, astunparse, tzlocal, soundfile, scikit-learn, pyflowchart, py-ecg-detectors, pooch, openpyxl, numba, nolds, mbstrdecoder, astropy, wfdb, typepy, statsmodels, pycwt, librosa, hrv-analysis, heartpy, dateparser, pmdarima, datetimerange, vital-sqi
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /home/miniconda3/envs/vital_exploratory/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      running build
      got version from file /tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
      running build_ext
      /home/miniconda3/envs/vital_exploratory/bin/python /tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py
      LLVM version... 14.0.0
      
      Traceback (most recent call last):
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 191, in <module>
          main()
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 181, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-h8sz9tgi/llvmlite_913a0b1a0397448cbb8db46c559ed13d/ffi/build.py", line 143, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '14.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
      
      error: command '/home/miniconda3/envs/vital_exploratory/bin/python' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by tiagofrepereira2012** [comment]
Fixed with https://github.com/meta00/vital_sqi/pull/99
